apiVersion: v1
kind: ConfigMap
metadata:
  name: bms-config
data:
 database_url: couchbase-service

---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: bms-deployment
    labels:
        app: bms
spec:
    replicas: 1
    selector:
        matchLabels:
            app: bms
    template:
        metadata:
            labels:
                app: bms
        spec:
            containers:
            - name: bms
              image: 277014/bankmanagementsystem:1.0
              env:
                - name: COUCHBASE_SERVICE_HOST
                  value: 127.0.0.1:8091
              ports:
              - containerPort: 8080
    
---
apiVersion: v1
kind: Service
metadata:
    name: bms-service
spec:
    selector:
      app: bms
    ports:
      - protocol: TCP
        port: 8080
        targetPort: 8080